// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {forms} from '../models';
import {plugin} from '../models';

export function AddOrUpdateProject(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function AddOrUpdateSchedule(arg1:models.Schedule):Promise<void>;

export function DealDebugSignal(arg1:string):Promise<void>;

export function DebugSubFlow(arg1:string,arg2:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteSubFlow(arg1:string,arg2:string):Promise<void>;

export function GetElementImage(arg1:string,arg2:string):Promise<string>;

export function GetLoginData():Promise<forms.LoginForm>;

export function GetMainFlow(arg1:string):Promise<{[key: string]: string}>;

export function GetNextTriggerTime(arg1:string):Promise<string>;

export function GetProjectWindowsElements(arg1:string):Promise<string>;

export function GetSelectedWindowsElement(arg1:string):Promise<string>;

export function GetSubFlow(arg1:string,arg2:string):Promise<string>;

export function GetWindowsElement(arg1:string,arg2:string):Promise<string>;

export function GetWindowsElementList(arg1:string):Promise<string>;

export function HighlightCurrentElement(arg1:string):Promise<void>;

export function ListProject():Promise<Array<models.Project>>;

export function Login(arg1:forms.LoginForm):Promise<void>;

export function OpenDialog(arg1:{[key: string]: string}):Promise<string>;

export function ParseAllPlugin():Promise<Array<plugin.Activity>>;

export function QuerySchedulePage():Promise<Array<models.Schedule>>;

export function RemoveSchedule(arg1:string):Promise<void>;

export function RemoveWindowsElement(arg1:string,arg2:string):Promise<void>;

export function RestartReplCommand(arg1:string):Promise<void>;

export function RunActivity(arg1:string,arg2:string):Promise<void>;

export function RunMainFlow(arg1:string):Promise<void>;

export function RunSubFlow(arg1:string,arg2:string):Promise<void>;

export function SaveMainFlow(arg1:string,arg2:string):Promise<void>;

export function SaveSubFlow(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveWindowsElement(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SelectProject(arg1:string):Promise<models.Project>;

export function StartCheck(arg1:string,arg2:string):Promise<string>;

export function StartCheckWindowsElement(arg1:string):Promise<string>;

export function StartPick():Promise<string>;

export function StartPickWindowsElement():Promise<string>;

export function TerminateSubFlow(arg1:string,arg2:string):Promise<void>;

export function ToggleScheduleById(arg1:string,arg2:boolean):Promise<void>;
