// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DeleteProject(arg1:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function ListProject(arg1:string,arg2:number):Promise<{[key: string]: any}>;

export function NewWorkflow(arg1:string):Promise<void>;

export function SelectProject(arg1:string):Promise<models.Project>;

export function UpdateProject(arg1:string,arg2:string):Promise<void>;
