// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddOrUpdateProject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddOrUpdateProject'](arg1, arg2, arg3, arg4);
}

export function DealDebugSignal(arg1) {
  return window['go']['main']['App']['DealDebugSignal'](arg1);
}

export function DebugSubFlow(arg1, arg2) {
  return window['go']['main']['App']['DebugSubFlow'](arg1, arg2);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteSubFlow(arg1, arg2) {
  return window['go']['main']['App']['DeleteSubFlow'](arg1, arg2);
}

export function GetElementImage(arg1, arg2) {
  return window['go']['main']['App']['GetElementImage'](arg1, arg2);
}

export function GetMainFlow(arg1) {
  return window['go']['main']['App']['GetMainFlow'](arg1);
}

export function GetProjectWindowsElements(arg1) {
  return window['go']['main']['App']['GetProjectWindowsElements'](arg1);
}

export function GetSelectedWindowsElement(arg1) {
  return window['go']['main']['App']['GetSelectedWindowsElement'](arg1);
}

export function GetSubFlow(arg1, arg2) {
  return window['go']['main']['App']['GetSubFlow'](arg1, arg2);
}

export function GetWindowsElement(arg1, arg2) {
  return window['go']['main']['App']['GetWindowsElement'](arg1, arg2);
}

export function GetWindowsElementList(arg1) {
  return window['go']['main']['App']['GetWindowsElementList'](arg1);
}

export function HighlightCurrentElement(arg1) {
  return window['go']['main']['App']['HighlightCurrentElement'](arg1);
}

export function ListProject(arg1, arg2) {
  return window['go']['main']['App']['ListProject'](arg1, arg2);
}

export function OpenDialog(arg1) {
  return window['go']['main']['App']['OpenDialog'](arg1);
}

export function ParseAllPlugin() {
  return window['go']['main']['App']['ParseAllPlugin']();
}

export function RemoveWindowsElement(arg1, arg2) {
  return window['go']['main']['App']['RemoveWindowsElement'](arg1, arg2);
}

export function RestartReplCommand(arg1) {
  return window['go']['main']['App']['RestartReplCommand'](arg1);
}

export function RunActivity(arg1, arg2) {
  return window['go']['main']['App']['RunActivity'](arg1, arg2);
}

export function RunMainFlow(arg1) {
  return window['go']['main']['App']['RunMainFlow'](arg1);
}

export function RunSubFlow(arg1, arg2) {
  return window['go']['main']['App']['RunSubFlow'](arg1, arg2);
}

export function SaveMainFlow(arg1, arg2) {
  return window['go']['main']['App']['SaveMainFlow'](arg1, arg2);
}

export function SaveSubFlow(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSubFlow'](arg1, arg2, arg3);
}

export function SaveWindowsElement(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveWindowsElement'](arg1, arg2, arg3, arg4);
}

export function SelectProject(arg1) {
  return window['go']['main']['App']['SelectProject'](arg1);
}

export function StartCheck(arg1, arg2) {
  return window['go']['main']['App']['StartCheck'](arg1, arg2);
}

export function StartCheckWindowsElement(arg1) {
  return window['go']['main']['App']['StartCheckWindowsElement'](arg1);
}

export function StartPick() {
  return window['go']['main']['App']['StartPick']();
}

export function StartPickWindowsElement() {
  return window['go']['main']['App']['StartPickWindowsElement']();
}

export function TerminateSubFlow(arg1, arg2) {
  return window['go']['main']['App']['TerminateSubFlow'](arg1, arg2);
}
