// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function GetMainFlow(arg1) {
  return window['go']['main']['App']['GetMainFlow'](arg1);
}

export function GetSubFlow(arg1, arg2) {
  return window['go']['main']['App']['GetSubFlow'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListProject(arg1, arg2) {
  return window['go']['main']['App']['ListProject'](arg1, arg2);
}

export function ParseAllPlugin() {
  return window['go']['main']['App']['ParseAllPlugin']();
}

export function SaveMainFlow(arg1, arg2) {
  return window['go']['main']['App']['SaveMainFlow'](arg1, arg2);
}

export function SaveSubFlow(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSubFlow'](arg1, arg2, arg3);
}

export function SelectProject(arg1) {
  return window['go']['main']['App']['SelectProject'](arg1);
}

export function UpdateProject(arg1, arg2) {
  return window['go']['main']['App']['UpdateProject'](arg1, arg2);
}
